

GET http://localhost:5150/api/logs
Content-Type: : application/json

###
GET http://localhost:5150/logs/9a6ff1dd-2998-44dc-9ba4-91045892e21b

###
POST http://localhost:5150/api/logs
Content-Type: application/json

{

}